name = "flaregram"
main = "src/index.js"
compatibility_date = "2023-05-18"
usage_model = "bundled"
env = { }

[dev]
host = "localhost"

# See Wiki for all env variable descriptions.
[vars]
# Mandatory Variables
BOT_TOKEN = ""
WEBHOOK_URL = ""
# Optional Parameters
SECRET_TOKEN = ""
DROP_PENDING_UPDATES = "True"
