name = "flaregram"
main = "src/index.js"
compatibility_date = "2023-05-18"
usage_model = "bundled"
env = { }

[dev]
host = "localhost"

# See readme.md for all env variable descriptions.
[vars]
BOT_TOKEN = "6292649461:AAFzeYuigzHq_Ois83RVoQD8vKe7rXgdC9k"
WEBHOOK_URL = "https://e252-117-214-223-63.ngrok-free.app/bot"
SECRET_TOKEN = "npnsqBKADK3D17oGTwCdfzbDPD2gqfDR0sRgRpFkHqsGJKnQjBCS7i_1uUUgGpWF"
DROP_PENDING_UPDATES = "True"
